# Generated by Django 4.1.1 on 2023-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='No product name', max_length=50)),
                ('item_description', models.TextField(default='No product description', max_length=1000)),
                ('item_image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sellers_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
